config/routes.rb
Rails.application.routes.draw do


  devise_for :vendors
  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Payola::Engine => '/payola', as: :payola
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  root 'basics#home'

  # BASIC NAVIGATION
  get 'contact' => 'basics#contact', as: :contact
  get 'Policies' => 'basics#policies', as: :policies
  get 'Shipping-Info' => 'basics#shipping_info', as: :shipping_info

  # PRODUCT LINES
  get 'products/embeds' => 'products#embeds', as: :embeds
  get 'products/embeds/:id' => 'products#embed_view', as: :embed

  get 'products/stabilizers/:id' => 'products#stabilizers_view', as: :stabilizer

  get 'products/chairs' => 'products#chairs', as: :chairs
  get 'products/chairs/:id' => 'products#chairs_view', as: :chair

  get 'products/studs' => 'products#studs', as: :studs
  get 'products/studs/:id' => 'products#studs_view', as: :stud

  get 'products/tracks/:id' => 'products#tracks_view', as: :track

  get 'products/tigerbeams' => 'products#beams', as: :beams

  # USER MAILER ESTIMATOR
  resources :contact_forms, only: [:new, :create]

  # ORDER HISTORY
  get 'orders' => 'orders#index', as: :orders
  get 'orders/:id' => 'orders#view', as: :order

  #SHOPPING CART
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  get 'cart' => 'carts#view', as: :cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart

  #ORDER PROCESSING I.E. CHECKOUT
  get 'checkout' => 'checkout#payment', as: :checkout
  post 'checkout' => 'checkout#process_payment', as: :process_payment
  get 'shipping' =>  'checkout#shipping', as: :shipping
  post 'shipping' => 'checkout#process_shipping', as: :process_shipping

  get 'receipts/:id' => 'checkout#receipt', as: :receipt


# VENDOR PANELS

get 'bss/orders' => 'bss#panel', as: :bss_panel
get 'bss/orders/:id' => 'bss#show', as: :bss_order

post 'bss/orders/:id' => 'bss#update', as: :bss_update

end

app/controllers/checkout_controller.rb
class CheckoutController < Wicked::WizardController
  include Wicked::Wizard
  steps :shipping

  before_action do
        if current_or_guest_user.nil?
          redirect_to sign_in_path
        end
      end

  def update
    @order = Order.find_by status: 'cart', user_id:current_or_guest_user.id
    @order.update_attributes(order_params)
    render_wizard @order
  end

  def payment
    @order = Order.find_by status: 'cart', user_id:current_or_guest_user.id
  end

  def process_payment

    @order = Order.find_by status: 'cart', user_id:current_or_guest_user.id
    @user = current_or_guest_user


    card_token = params[:stripeToken]

    Stripe.api_key = "sk_live_rBUFnaNVloLy6YhyhEDJx5O4"

    Stripe::Charge.create(
      :amount => @order.final_price,
      :currency => "usd",
      :source => card_token,
    )


    if @order.email.present?
    @order.update status: 'pending'
    ReceiptMailer.order_confirmation(@user, @order).deliver_now
    redirect_to receipt_path(id: @order.id)
    else
      @order.update status: 'pending'
      redirect_to receipt_path(id: @order.id)
    end

  end

  def receipt
    @order = Order.find_by! id: params[:id], user_id: current_or_guest_user.id
  end

  private
    def order_params
      params.require(:orders).permit(:address_zip, :address_city, :address_state, :address_line1, :phone_number, :name, :shipping_cost, :email)
    end

    private

    def redirect_to_finish_wizard
      redirect_to payment_payment, notice: "Thank You for Your Information"
    end
end

app/views/checkout/cart_view.html.erb
<%= render '/layouts/alt_nav.html.erb'%>

<div class="cart-container" style="margin-bottom:18%;">


  <div class="bag-container">
    <div class="bag">
      <div class="bag-title">
        SHOPPING BAG ITEMS (<%= @order.order_items.count %>)
      </div>

      <table>
        <thead>
          <tr>
            <th>
            </th>
            <th>
              Product
            </th>
            <th>
              Quantity
            </th>

            <th>
              Price
            </th>
            <th>
              Total
            </th>
            <th>
              Remove
            </th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.each do |order_item| %>

          <tr>
            <td>
              <%= image_tag "#{order_item.img_file}.jpg", {:class => "cart_picture"}%>
            </td>
            <td>
              <%= order_item.name %>
            </td>
            <td>
              <%= order_item.quantity%>

            </td>
            <td>
              <%= number_to_currency(order_item.price) %>
            </td>
            <td>
              <%= number_to_currency order_item.item_price %>
            </td>
            <td>
              <%= link_to 'Remove Item', remove_from_cart_path(product_id: order_item.product_id), method: :delete, class: "remove-cart" %>
            </td>
          </tr>

          <% end %>

        </tbody>
      </table>


    </div>

    <div class="summary">
      <div class="bag-title">
        ORDER SUMMARY
      </div>
      <div class="summary-values">
        Subtotal:<%=number_to_currency(@order.subtotal) %></br>
      </div>

      <div class="summary-values">
        Shipping: $0.00 TBD</br>

      </div>
      <div class="summary-values">
        Tax: $0.00 (TBD)

      </div>
      <div class="summary-values-black">
        Total: <%= number_to_currency(@order.subtotal) %>
      </div>
      <% if @order.cart_total > 0 %>
      <%= link_to 'CHECKOUT', shipping_path, class: 'checkout-btn' %>
      <%else%>
      <%= link_to 'FIND EMBEDS?', products_path, class:'checkout-btn' %>
      <%end%>
    </div>
  </div>



</div>
<%= render '/layouts/footer.html.erb'%>

app/views/checkout/payment.html.erb
<div class="checkout-nav">
  <div class="nav-logo">
  <%= link_to root_path do %><%= image_tag "logo.jpg"%><%end%>
  </div>
</div>
<div class="checkout-phone">
  <i class="fa fa-mobile fa-2x" aria-hidden="true"></i>
  281.583.7088
</div>
<div class="checkout-title">
  CHECKOUT
</div>
<div class="shipping-container">
  <div class="shipping" style="margin-right:15px;">
    <div class="summary-title">
      <div class="">
        1. SHIPPING
      </div>
        <%= link_to "EDIT", shipping_path %>

    </div>
    <div class="shipping-1">

      <div class="shipping-title">
        2. PAYMENT
      </div>


      <div class="shipping-content">

      <%= form_tag process_payment_path, method: :post, id: "payment-form" do %>

        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_live_JcBfnty8T16X7StsmKRGP4Wb"
          data-name="Nirvana Products"
          data-image=<%= image_url('logo_alt.jpg')  %>
          data-amount="<%= @order.final_price %>"
          <% if @order.email.present?%>
          data-email="<%= @order.email %>"
          <%else%>
          data-email="true"
          <%end%>
          data-billing-address="true"
          data-locale="auto"
          data-statement-descriptor="Nirvana Products" >
        </script>
<script>
$(document).ready(function() {
  $(".stripe-button-el").click();
})
</script>
      <% end %>

      <% if false %>



        <%= form_tag process_payment_path, method: :post, id: "payment-form" do %>
        <span class="payment-errors"></span>
        <div id="error_explanation">
          <% if flash[:error].present? %>
          <p><%= flash[:error] %></p>
          <% end %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Name<span>*</span>
          </div>
          <%= text_field_tag :name, "", class: "name" %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Card Number<span>*</span>
          </div>
          <%= text_field_tag :credit_card_number, "", class: "card-number" %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Expiry Date<span>*</span>
          </div>
          <%= select_month Date.today, {}, class: "card-expiry-month" %>  <%= select_year Date.today, {start_year: Date.today.year, end_year: Date.today.year+20}, class: "card-expiry-year" %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Security Code<span>*</span>
          </div>
          <%= number_field_tag :cvc, "",class: "card-cvc"%>
        </div>

        <div class="summary-title">
          BILLING
        </div>
        <div class="section">
          <div class="shipping-label">
            Address Line 1<span>*</span>
          </div>
          <%= text_field_tag :stripeBillingAddressLine1, "", class: "card-address" %>
        </div>

        <div class="section">
          <div class="shipping-label">
            City<span>*</span>
          </div>
          <%= text_field_tag :stripeBillingAddressCity, "", class: "card-city" %>
        </div>

        <div class="section">
          <div class="shipping-label">
            State<span>*</span>
          </div>
            <%= select_tag(:stripeBillingAddressState, options_for_select(us_states, "TX"),{ :class => 'card-state' }) %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Zip<span>*</span>
          </div>
          <%= text_field_tag :stripeBillingAddressZip, "", class: "card-zip" %>
        </div>


        <%= submit_tag 'PURCHASE', class:'next-step' %>
        <div class="required">
          <span>*</span>
          Required Field

        </div>

        <%end%>
        <%end%>
      </div>

    </div>

    <div class="summary-title" style="margin-top:20px;">
      3. RECEIPT
    </div>

  </div>
  <div class="summary-main-container">

    <div class="summary-checkout">
      <div class="summary-title">
        SUMMARY
      </div>
      <div class="summary-content">
        <div class="piece">
          <div class="item">
            SUBTOTAL
          </div>
          <div class="item-2">
            <%= number_to_currency(@order.subtotal) %>
          </div>
        </div>
        <div class="piece">
          <div class="item">
            ESTIMATED SHIPPING
          </div>
          <div class="item-2">
            <%= number_to_currency(@order.total_shipping)%>
          </div>
        </div>
        <div class="piece">
          <div class="item" style="color:#7f8c8d">
            TAX
          </div>
          <div class="item-2" style="color:#7f8c8d">
            <% if @order.address_state = "TX" %>
            <%= number_to_currency(@order.total_tax) %>
            <%else%>
            TAX: $0.00
            <%end%>
          </div>
        </div>
        <div class="piece-total">
          <div class="item">
            TOTAL </br>
            <%= link_to "Shipping Information", shipping_info_path, :target => "_blank"%>
          </div>
          <div class="item-total">
            <%= number_to_currency(@order.final_price * 0.01) %>
          </div>
        </div>
      </div>

    </div>

    <div class="current-cart">
      <div class="summary-title" style="margin-top:20px;margin-bottom:40px;">
        IN YOUR CART
      </div>
        <% @order.order_items.each do |order_item| %>
        <div style="display:flex">

        <%= image_tag "#{order_item.img_file}.jpg", {:class => "checkout_picture"}%>
        <div class="checkout-item-info">
          <span style="font-family:'Open Sans',sans-serif"><%= order_item.name %></span>

          <span>Quantity: <%= order_item.quantity%></span>

          <span>Item Price: <%= number_to_currency(order_item.price.to_i) %></span>

          <span style="color:#F76122; font-family:'Open Sans',sans-serif">Total Price: <%= number_to_currency order_item.item_price %></span>
        </div>
      </div>



<%end%>
</div>
  </div>

</div>

<%= render "layouts/footer.html.erb" %>

app/views/checkout/receipt.html.erb
<%= render '/layouts/alt_nav.html.erb'%>
<div class="receipt-container">

<p class="receipt-header">RECEIPT #<%= @order.id %></p>

<div class="thank-you">
  THANK YOU FOR YOUR PURCHASE
</div>
  <div class="" style="Font-family:'Open Sans', sans-serif; font-size:18px; text-align:center;margin-top:30px;">
  We sent a receipt to your email <strong> <%= @order.email %></strong>. Your load tables, sign and seals and shop drawings will be emailed to you shortly. If you do not recieve an email within 12 hours, please feel free to call us at 832-483-2131 or email us at nirconrd@gmail.com
</div>



</div>
<div class="bag-container" style="margin-top:100px;">
  <div class="bag">
    <div class="receipt-line">Purchaser: <%= @order.email %></div>
    <div class="receipt-line">Purchase Date : <%= local_time(@order.purchased_at) %></div>
    <div class="receipt-line">Order ID : <%= @order.id %></div>
    <div class="bag-title">
      YOUR PURCHASE
    </div>

    <table>
      <thead>
        <tr>
          <th>
            Item
          </th>
          <th>
            Name
          </th>
          <th>
            Quantity
          </th>

          <th>
            Per Item Price
          </th>


          <th>
            Total Shipping Cost
          </th>

          <th>
            Total Price
          </th>
        </tr>
      </thead>

      <tbody>
        <% @order.order_items.each do |order_item| %>

        <tr>
          <td>
            <%= image_tag "#{order_item.img_file}.jpg", {:class => "cart_picture"}%>
          </td>
          <td>
            <%= order_item.name %>
          </td>
          <td>
            <%= order_item.quantity %>
          </td>

          <td>
            <%= number_to_currency(order_item.price.to_i) %>
          </td>

          <% end %>
          <td>
            <%= number_to_currency(@order.total_shipping) %>
          </td>
          <td>
            <%= number_to_currency(@order.total_price_in_cents * 0.01) %>
          </td>
        </tr>



      </tbody>
    </table>
  </div>
</div>
</div>

<%= render '/layouts/footer.html.erb' %>

app/views/checkout/shipping.html.erb
<div class="checkout-nav">
  <div class="nav-logo">
  <%= link_to root_path do %><%= image_tag "logo.jpg"%><%end%>
  </div>

</div>
<div class="checkout-phone">
  <i class="fa fa-mobile fa-2x" aria-hidden="true"></i>
  281.583.7088
</div>
<div class="checkout-title">
  CHECKOUT
</div>
<% flash.each do |name,msg| %>
<%= content_tag :div, msg, :id => "flash", class: 'flash-message' %>
<%end%>
<div class="shipping-container">
  <div class="shipping">

    <div class="shipping-1">

      <div class="shipping-title">
        1. SHIPPING
      </div>

      <div class="shipping-content">
        <%= form_for :orders, :url=> process_shipping_path, method: :post do |f| %>
        <div class="section">
          <div class="shipping-label">
            Name<span>*</span>
          </div>
          <%= f.text_field :name, class:'shipping-param' %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Email<span>*</span>
          </div>
          <%= f.text_field :email, class:'shipping-param' %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Address<span>*</span>
          </div>
          <%= f.text_field :address_line1, class:'shipping-param' %>
        </div>
        <div class="section">
          <div class="shipping-label">
            City<span>*</span>
          </div>
          <%= f.text_field :address_city, class:'shipping-param' %>
        </div>
        <div class="section">
          <div class="shipping-label">
            State<span>*</span>
          </div>
          <%= f.select(:address_state, options_for_select(us_states, "TX"))%>
        </div>
        <div class="section">
          <div class="shipping-label">
            ZIP Code<span>*</span>
          </div>
          <%= f.text_field :address_zip, class:"shipping-param" %>
        </div>
        <div class="section">
          <div class="shipping-label">
            Phone Number<span>*</span>
          </div>
          <%= f.text_field :phone_number, class:"shipping-param", name:"phone_number" %>
        </div>

        <%= f.submit "TO BILLING", :class =>'next-step', :id => 'register', :disabled => 'disabled'%>
        <div class="required">
          <span>*</span>
          Required Field
        </div>
        <%end%>
      </div>

    </div>



    <div class="summary-title" style="margin-top:20px;">
      2. PAYMENT
    </div>

    <div class="summary-title" style="margin-top:20px;">
      3. RECEIPT
    </div>

  </div>
  <div class="summary-main-container">

    <div class="summary-checkout">
      <div class="summary-title">
        SUMMARY
      </div>
      <div class="summary-content">
        <div class="piece">
          <div class="item">
            SUBTOTAL
          </div>
          <div class="item-2">
            <%= number_to_currency(@order.subtotal) %>
          </div>
        </div>
        <div class="piece">
          <div class="item">
            ESTIMATED SHIPPING
          </div>
          <div class="item-2">
            $0.00 (TBD)
          </div>
        </div>
        <div class="piece">
          <div class="item">
            TAX
          </div>
          <div class="item-2">
          $0.00 (TBD)
          </div>
        </div>
        <div class="piece-total">
          <div class="item">
            TOTAL
          </div>
          <div class="item-total">
            <%= number_to_currency(@order.subtotal) %>
          </div>
        </div>
      </div>

    </div>

    <div class="current-cart">
      <div class="summary-title" style="margin-top:20px;margin-bottom:40px;">
        IN YOUR CART
      </div>

          <% @order.order_items.each do |order_item| %>
          <div class="cc-container">
        <%= image_tag "#{order_item.img_file}.jpg", {:class => "checkout_picture"}%>
        <div class="checkout-item-info">
          <span style="font-family: 'Open Sans', sans-serif; font-weight:400;"><%= order_item.name %></span>

          <span>Quantity: <%= order_item.quantity%></span>

          <span>Item Price: <%= number_to_currency(order_item.price) %></span>

          <span style="font-family: 'Open Sans', sans-serif; font-weight:400;">Total Price: <%= number_to_currency order_item.item_price %></span>
        </div>
      </div>


<%end%>
</div>

  </div>

</div>

<%= render "layouts/footer.html.erb" %>

<script type="text/javascript">
(function() {
    $('.shipping-param').keyup(function() {

        var empty = false;
        $('.shipping-param').each(function() {
            if ($(this).val() == '') {
                empty = true;
            }
        });

        if (empty) {
            $('#register').attr('disabled', 'disabled'); // updated according to http://stackoverflow.com/questions/7637790/how-to-remove-disabled-attribute-with-jquery-ie
        } else {
            $('#register').removeAttr('disabled'); // updated according to http://stackoverflow.com/questions/7637790/how-to-remove-disabled-attribute-with-jquery-ie
        }
    });
})()
</script>

<script type="text/javascript">
$("input[name='phone_number']").keyup(function() {
  $(this).val($(this).val().replace(/^(\d{3})(\d{3})(\d)+$/, "($1)-$2-$3"));
});
</script>

app/views/checkout/start.html.erb
<div class="checkout-container" style="margin-bottom:16%;">

  <%= render '/products/alt_nav.html.erb'%>


  <div class="bag-container" style="margin-top:100px;padding-left:0px; margin-left:60px;">
    <div class="bag">
      <div class="bag-title">
        YOUR ITEMS
      </div>

      <table>
        <thead>
          <tr>
            <th>
              Item
            </th>
            <th>
              Name
            </th>
            <th>
              Quantity
            </th>

            <th>
              Per Item Price
            </th>

            <th>
              Shipping Per Item
            </th>
            <th>
              Total Shipping Cost
            </th>
            <th>
              Subtotal
            </th>
            <th>
              Total Price
            </th>
          </tr>
        </thead>

        <tbody>
          <% @order.order_items.each do |order_item| %>

          <tr>
            <td>
              <%= image_tag "#{order_item.img_file}.jpg", {:class => "cart_picture"}%>
            </td>
            <td>
              <%= order_item.name %>
            </td>
            <td>
              <%= order_item.quantity %>
            </td>

            <td>
              <%= number_to_currency(order_item.price.to_i) %>
            </td>
            <td>
              <%= number_to_currency(order_item.shipping_cost.to_i) %>
            </td>
            <td>
              <%= number_to_currency(order_item.total_shipping.to_i) %>
            </td>
            <td>
              <%= number_to_currency(order_item.subtotal_price.to_i) %>
            </td>
            <td>
              <%= number_to_currency(order_item.total_price.to_i) %>
            </td>

          </tr>

          <% end %>

        </tbody>
      </table>
    </div>
  </div>
  <div class="bag-title" style="width:20%;margin-left:60px;margin-top:50px;">CHECKOUT</div>
<%= form_tag process_payment_path, method: :post, id: 'payment-form' do %>
  <script src="https://checkout.stripe.com/checkout.js"
  class="customButton"
  data-key="pk_test_UQ02f5WGJ1E2k2sUXLJcqn4C"
  ></script>
  <%= hidden_field_tag 'stripeToken' %>
  <%= hidden_field_tag 'stripeEmail' %>
  <button id="customButton">Pay with Card  <i class="fa fa-arrow-circle-o-right fa-lg" aria-hidden="true"></i></button>

  <script>
    var handler = StripeCheckout.configure({
      key: '<%= ENV["pk_test_UQ02f5WGJ1E2k2sUXLJcqn4C"] %>',
      token: function(token, args) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("payment-Form").submit();
      }
    });

    document.getElementById('customButton').addEventListener('click', function(e) {
      // Open Checkout with further options
      handler.open({
        name: 'Nirvana Construction',
        amount: <%=@order.total_price_in_cents%>,
        shippingAddress: true,
        description: '<%=@order.description%>'
      });
      e.preventDefault();
    });
  </script>
<% end %>
<%= render '/layouts/alt_footer.html.erb'%>