config/routes.rb
Rails.application.routes.draw do


  devise_for :vendors
  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Payola::Engine => '/payola', as: :payola
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  root 'basics#home'

  # BASIC NAVIGATION
  get 'contact' => 'basics#contact', as: :contact
  get 'Policies' => 'basics#policies', as: :policies
  get 'Shipping-Info' => 'basics#shipping_info', as: :shipping_info

  # PRODUCT LINES
  get 'products/embeds' => 'products#embeds', as: :embeds
  get 'products/embeds/:id' => 'products#embed_view', as: :embed

  get 'products/stabilizers/:id' => 'products#stabilizers_view', as: :stabilizer

  get 'products/chairs' => 'products#chairs', as: :chairs
  get 'products/chairs/:id' => 'products#chairs_view', as: :chair

  get 'products/studs' => 'products#studs', as: :studs
  get 'products/studs/:id' => 'products#studs_view', as: :stud

  get 'products/tracks/:id' => 'products#tracks_view', as: :track

  get 'products/tigerbeams' => 'products#beams', as: :beams

  # USER MAILER ESTIMATOR
  resources :contact_forms, only: [:new, :create]

  # ORDER HISTORY
  get 'orders' => 'orders#index', as: :orders
  get 'orders/:id' => 'orders#view', as: :order

  #SHOPPING CART
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  get 'cart' => 'carts#view', as: :cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart

  #ORDER PROCESSING I.E. CHECKOUT
  get 'checkout' => 'checkout#payment', as: :checkout
  post 'checkout' => 'checkout#process_payment', as: :process_payment
  get 'shipping' =>  'checkout#shipping', as: :shipping
  post 'shipping' => 'checkout#process_shipping', as: :process_shipping

  get 'receipts/:id' => 'checkout#receipt', as: :receipt


# VENDOR PANELS

get 'bss/orders' => 'bss#panel', as: :bss_panel
get 'bss/orders/:id' => 'bss#show', as: :bss_order

post 'bss/orders/:id' => 'bss#update', as: :bss_update

end

app/controllers/bss_controller.rb
class BssController < ApplicationController
  before_action :authenticate_vendor!
  def panel
    @orders = Order.where('(status=?) OR (status=?) OR (status=?) OR (status=?)', 'pending', 'shipped', 'canceled', 'complete')

  end

  def show
  @order = Order.find_by id: params[:id]
  end

  def update
    @order = Order.find_by id: params[:id]
    @order.update_attributes(order_params)
    if @order.save
      flash[:success] = "Successfully Edited Order"
      redirect_to request.referrer
    end
  end


private
def order_params
  params.require(:order).permit(:status, :address_line1, :address_city, :address_zip, :address_state, :name,:phone_number)
end
end

app/helpers/bss_helper.rb
module BssHelper
  def status
    [
      ['pending','pending'],
      ['shipped','shipped'],
      ['complete','complete'],
      ['canceled','canceled']
    ]
  end
end

app/views/bss/panel.html.erb
<div class="vendor_container">
<div class="vendor_header">
BLACK SWAN STEEL <span>Admin</span>
<span><%= link_to destroy_vendor_session_path, :method => "delete" do %>
      <i class="fa fa-times-circle-o" aria-hidden="true"></i>
      SIGN OUT
      <%end %></span>
</div>
<div class="vendor_title">
  Select Order To View or Edit
</div>

<div class="vendor_table_container">

<table>
  <thead>
    <tr>
      <th>
      ID
      </th>
      <th>
        STATUS
      </th>
      <th>
        PURCHASE DATE
      </th>

      <th>
        Name
      </th>
      <th>
        State
      </th>
      <th>
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </th>

    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>

    <tr>
      <td>
        <%= order.id %>
      </td>
      <td>
        <%= order.status %>
      </td>
      <td>
        <%= local_time(order.purchased_at) %>
      </td>
      <td>
        <%= order.name %>

      </td>
      <td>
        <%= order.address_state %>
      </td>

        <td>
          <%= link_to "Show More/Edit", bss_order_path(id: order.id) %>
        </td>

    </tr>

  </tbody>
</table>
</div>

<%end%>

</div>

app/views/bss/show.html.erb
<div class="vendor_header">
BLACK SWAN STEEL <span>Admin</span>
</div>
<div class="vendor_title">
  <%= link_to "Orders", bss_panel_path %> <i class="fa fa-list" aria-hidden="true"></i>
 / View and Edit Order <i class="fa fa-pencil" aria-hidden="true"></i>/ #<%= @order.id %>
</div>
<% flash.each do |name,msg| %>
<%= content_tag :div, msg, :id => "flash", class: 'flash-message' %>
<%end%>
<div class="orders-table" style="margin-left:10%; margin-right:10%;">
  <div class="orders-items">Order Items</div>

<table>
  <thead>
    <tr>
      <th>
        Item
      </th>
      <th>
        Name
      </th>
      <th>
        Quantity
      </th>

      <th>
        Per Item Price
      </th>


      <th>
        Total Shipping Cost
      </th>

      <th>
        Total Price
      </th>
    </tr>
  </thead>

  <tbody>
    <% @order.order_items.each do |order_item| %>

    <tr>
      <td>
        <%= image_tag "#{order_item.img_file}.jpg", {:class => "cart_picture"}%>
      </td>
      <td>
        <%= order_item.name %>
      </td>
      <td>
        <%= order_item.quantity %>
      </td>

      <td>
        <%= number_to_currency(order_item.price.to_i) %>
      </td>

      <% end %>
      <td>
        <%= number_to_currency(@order.total_shipping) %>
      </td>
      <td>
        <%= number_to_currency(@order.final_price * 0.01) %>
      </td>
    </tr>



  </tbody>
</table>

</div>

<%= form_for @order, :url => bss_update_path, method: :post do |f|%>

<div class="bss_form"><span>User</span><%= f.text_field :name %></div>
<div class="bss_form"><span>Address Line 1</span><%= f.text_field :address_line1 %></div>
<div class="bss_form"><span>Zip Code</span><%= f.text_field :address_zip %></div>
<div class="bss_form"><span>City </span><%= f.text_field :address_city %></div>
<div class="bss_form"><span>State</span><%= f.select(:address_state, options_for_select(us_states, "TX"))%></div>
<div class="bss_form"><span>Status</span><%= f.select(:status, options_for_select(status, "Pending"))%></div>
<div class="bss_form">
  <%= f.submit "UPDATE", class:'bss_submit' %>
</div>
<%end%>