config/routes.rb
Rails.application.routes.draw do


  devise_for :vendors
  devise_for :users
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Payola::Engine => '/payola', as: :payola
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  root 'basics#home'

  # BASIC NAVIGATION
  get 'contact' => 'basics#contact', as: :contact
  get 'Policies' => 'basics#policies', as: :policies
  get 'Shipping-Info' => 'basics#shipping_info', as: :shipping_info

  # PRODUCT LINES
  get 'products/embeds' => 'products#embeds', as: :embeds
  get 'products/embeds/:id' => 'products#embed_view', as: :embed

  get 'products/stabilizers/:id' => 'products#stabilizers_view', as: :stabilizer

  get 'products/chairs' => 'products#chairs', as: :chairs
  get 'products/chairs/:id' => 'products#chairs_view', as: :chair

  get 'products/studs' => 'products#studs', as: :studs
  get 'products/studs/:id' => 'products#studs_view', as: :stud

  get 'products/tracks/:id' => 'products#tracks_view', as: :track

  get 'products/tigerbeams' => 'products#beams', as: :beams

  # USER MAILER ESTIMATOR
  resources :contact_forms, only: [:new, :create]

  # ORDER HISTORY
  get 'orders' => 'orders#index', as: :orders
  get 'orders/:id' => 'orders#view', as: :order

  #SHOPPING CART
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  get 'cart' => 'carts#view', as: :cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart

  #ORDER PROCESSING I.E. CHECKOUT
  get 'checkout' => 'checkout#payment', as: :checkout
  post 'checkout' => 'checkout#process_payment', as: :process_payment
  get 'shipping' =>  'checkout#shipping', as: :shipping
  post 'shipping' => 'checkout#process_shipping', as: :process_shipping

  get 'receipts/:id' => 'checkout#receipt', as: :receipt


# VENDOR PANELS

get 'bss/orders' => 'bss#panel', as: :bss_panel
get 'bss/orders/:id' => 'bss#show', as: :bss_order

post 'bss/orders/:id' => 'bss#update', as: :bss_update

end

app/views/layouts/_alt_nav.html.erb
<div class="nav" id="navbar">
  <p class="nav-logo">
    <%= link_to root_path do%><%= image_tag "logo.jpg" %><%end%>
  </p>
  <div class="nav-items">
    <div class="dropdown">
      <button class="dropbtn">Products
        <i class="fa fa-chevron-down" aria-hidden="true"></i>
      </button>
      <div class="dropdown-content" id="myDropdown">
        <%= link_to embeds_path do %>
        EASY EMBEDS
        <%end%>
        <%= link_to chairs_path do %>
        COLORED CHAIRS
        <%end %>
        <%= link_to studs_path do %>
        STANDARD STUDS
        <%end %>
        <%= link_to beams_path do %>
        TIGER BEAMS
        <%end %>
      </div>
    </div>


    <%= link_to "About Us","#{root_path}#codeword"%>


    <%= link_to "Plan Upload/Custom Order", new_contact_form_path, class:'nav-item-b' %>

    <%= link_to cart_path do %>
    View Cart <i class="fa fa-shopping-cart" aria-hidden="true" id='cart-nav'></i>
    <%end%>
  </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">

  <div class="footer-logo">
    <%= image_tag "logo.jpg" %>
  </div>

  <div class="social">
    <i class="fa fa-cc-mastercard fa-2x" aria-hidden="true"></i>
    <i class="fa fa-cc-visa fa-2x" aria-hidden="true"></i>
    <i class="fa fa-cc-discover fa-2x" aria-hidden="true"></i>
    <i class="fa fa-cc-amex fa-2x" aria-hidden="true"></i>
  </div>
  <div class="copyright">
    Copyright ©  2016 by Nirvana Construction. All Rights Reserved</br> <%= link_to "Contact Us", contact_path, class:"contact-footer-link"%>
     <%= link_to "Shipping Info", shipping_info_path, class:"contact-footer-link"%>
  </div>

</div>

app/views/layouts/_nav_bar.html.erb
<div class="nav" id="navbar">
  <p class="nav-logo">
    <%= link_to root_path do%><%=image_tag "logo.jpg"%> <%end%>
  </p>
  <div class="nav-items">

    <div class="dropdown">
      <button class="dropbtn">Products
        <i class="fa fa-chevron-down" aria-hidden="true"></i>
      </button>
      <div class="dropdown-content" id="myDropdown">
        <%= link_to embeds_path do %>
        EASY EMBEDS
        <%end%>
        <%= link_to chairs_path do %>
        COLORED CHAIRS
        <%end %>
        <%= link_to studs_path do %>
        STANDARD STUDS
        <%end %>
        <%= link_to beams_path do %>
        TIGER BEAMS
        <%end %>
      </div>
    </div>

    <% if current_page?(root_url)%>
    <A HREF="#codeword">About Us</A>
    <%else%>
    <%= link_to "About Us","#{root_path}#codeword"%>
    <%end%>

    <%= link_to "Plan Upload/Custom Order", new_contact_form_path, class:'nav-item-a' %>


    <% if user_signed_in? %>
    <div class="dropdown">
      <button class="dropbtn"><%= current_user.email %>
        <i class="fa fa-chevron-down" aria-hidden="true"></i>
      </button>
      <div class="dropdown-content" id="myDropdown">
        <%= link_to orders_path do %>

        ORDERS
        <%end%>
        <%= link_to destroy_user_session_path, :method => "delete" do %>
        <i class="fa fa-times-circle-o" aria-hidden="true"></i>
        SIGN OUT
        <%end %>
      </div>
    </div>

    <%else%>
    <%= link_to "Sign In/Create Account", new_user_session_path, class:'nav-item-a' %>
    <%end%>
    <%= link_to cart_path do %>
     View Cart <i class="fa fa-shopping-cart" aria-hidden="true" id='cart-nav'></i>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nirvana Construction Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600,800" rel="stylesheet">
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-84497632-1', 'auto');
    ga('send', 'pageview');

  </script>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript" src=" https://checkout.stripe.com/checkout.js"></script>
  <script type="text/javascript">
    Stripe.setPublishableKey('pk_live_JcBfnty8T16X7StsmKRGP4Wb');
  </script>
  <script type="text/javascript">
  $(window).load(function() {
  	$(".loader").delay(1000).hide(0);
  })
  </script>
<%= favicon_link_tag 'favicon-32x32.png', sizes:'32x32'%>
<%= favicon_link_tag 'favicon-16x16.png', sizes:'16x16'%>
<%= favicon_link_tag 'favicon-128.png', sizes:'128x128'%>
<%= favicon_link_tag 'apple-touch-icon-57x57.png', rel:'apple-touch-icon-precomposed', sizes:'57x57' %>
<%= favicon_link_tag 'apple-touch-icon-114x114.png', rel:'apple-touch-icon-precomposed', sizes:'114x114' %>
<%= favicon_link_tag 'apple-touch-icon-72x72.png', rel:'apple-touch-icon-precomposed', sizes:'72x72' %>
<%= favicon_link_tag 'apple-touch-icon-144x144.png', rel:'apple-touch-icon-precomposed', sizes:'144x144' %>
<%= favicon_link_tag 'apple-touch-icon-60x60.png', rel:'apple-touch-icon-precomposed', sizes:'60x60' %>
<%= favicon_link_tag 'apple-touch-icon-120x120.png', rel:'apple-touch-icon-precomposed', sizes:'120x120' %>
<%= favicon_link_tag 'apple-touch-icon-76x76.png', rel:'apple-touch-icon-precomposed', sizes:'76x76' %>
<%= favicon_link_tag 'apple-touch-icon-52x52.png', rel:'apple-touch-icon-precomposed', sizes:'52x52' %>
<%= favicon_link_tag 'favicon-196x196.png', type:'image/png',sizes:'196x196'%>
<%= favicon_link_tag 'favicon-96x96.png', type:'image/png',sizes:'96x96'%>
</head>
<body>

  <!--  NAV-->
  <div class="loader">
  </div>
<%= yield %>
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>http://localhost:3000</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration>
</body>

<script type="text/javascript">
$(document).ready(function () {
  setTimeout(function () {
    $('#flash').remove();
  }, 2500);

})
</script>




</html>

app/views/layouts/nav_bar_original.html.erb
<div class="nav" id="navbar">
  <p class="nav-logo">
    <%= link_to root_path do%><%=image_tag "logo.jpg"%> <%end%>
  </p>
  <div class="nav-items">

    <%= link_to "Easy Embeds", products_path, class:'nav-item-a'%>
    <%= link_to "Colored Chairs", chairs_path, class:'nav-item-a'%>
    <%= link_to "Tiger Tracks", beams_path, class:'nav-item-a'%>

    <%= link_to "Plan Upload/Custom Order", new_message_path, class:'nav-item-b' %>

    <% if user_signed_in? %>
    <div class="dropdown">
      <button class="dropbtn"><%= current_user.email %>
        <i class="fa fa-chevron-down" aria-hidden="true"></i>
      </button>
      <div class="dropdown-content" id="myDropdown">
        <%= link_to orders_path do %>
        <i class="fa fa-list-alt" aria-hidden="true"></i>
        ORDERS
        <%end%>
        <%= link_to destroy_user_session_path, :method => "delete" do %>
        <i class="fa fa-times-circle-o" aria-hidden="true"></i>
        SIGN OUT
        <%end %>
      </div>
    </div>

    <%else%>
    <%= link_to "Sign In", new_user_session_path, class:'nav-item-a' %>
    <%end%>
    <%= link_to cart_path do %>
    View Cart <i class="fa fa-shopping-cart" aria-hidden="true" id='cart-nav'></i>
    <%end%>
  </div>
</div>